package com.upo.ebank.model.enums;

public enum RightName {
    VIEW_CLIENTS,
    EDIT_CLIENTS,
    VIEW_EMPLOYEES,
    VIEW_ACCOUNTS,
    MANAGE_ACCOUNTS,
    EDIT_EMPLOYEES,
    USER_RIGHTS,
    VIEW_LOANS,
    APPROVE_LOANS,
    EMPLOYEE_RIGHTS,
    VIEW_DEPOSITS,
    VIEW_TRANSACTIONS,
}
